/*
 * ® Copyright 2017 Haoran Wang. All rights reserved.
 *  
 * The works in this project are licenced under a 
 * Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported 
 * (CC BY-NC-SA 3.0) Licence.
 * 
 * That is to say, you may freely modify the work, quote the content of the work, 
 * and use it for other purposes, as long as it's non-commercial. 
 * If you want to distribute the work, you need to give appropriate credit and make 
 * sure it is under the same licence as the original, 
 * in this case, a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0) Licence should be applied.
 */


package haoran.wang.mailClient;

/**
 *
 * @author HaoranWang
 */
public class ManageGUI extends javax.swing.JFrame {

    static String nameofEmail1;
    static String nameofEmail2;
    static String nameofEmail3;
    static String nameofEmail4;
    static String nameofEmail5;
    
    
    final void initialize()
    {   
        // you can make this recursive if you want
        switch(data.numOfEmail)
        {
            case 1: email1Label.setText(nameofEmail1);
            case 2: 
            {
                email1Label.setText(nameofEmail1);
                email2Label.setText(nameofEmail2);
            }
            case 3:
            {
                email1Label.setText(nameofEmail1);
                email2Label.setText(nameofEmail2);
                email3Label.setText(nameofEmail3);
            }
            case 4:
                email1Label.setText(nameofEmail1);
                email2Label.setText(nameofEmail2);
                email3Label.setText(nameofEmail3);
                email4Label.setText(nameofEmail4);
            case 5: 
                email1Label.setText(nameofEmail1);
                email2Label.setText(nameofEmail2);
                email3Label.setText(nameofEmail3);
                email4Label.setText(nameofEmail4);
                email5Label.setText(nameofEmail5);
        }
        
    }
    
    
    
    
    
    
    /**
     * Creates new form ManageGUI
     */
    public ManageGUI() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabelManageGUI = new javax.swing.JLabel();
        addJButtonManageGUI = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        email1Button = new javax.swing.JButton();
        email2Button = new javax.swing.JButton();
        email3Button = new javax.swing.JButton();
        email4Button = new javax.swing.JButton();
        email5Button = new javax.swing.JButton();
        email1Label = new javax.swing.JLabel();
        email2Label = new javax.swing.JLabel();
        email3Label = new javax.swing.JLabel();
        email4Label = new javax.swing.JLabel();
        email5Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 450));
        setMinimumSize(new java.awt.Dimension(630, 450));
        setResizable(false);

        titleJLabelManageGUI.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titleJLabelManageGUI.setText("Manage Your Accounts");

        addJButtonManageGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        addJButtonManageGUI.setText("Add");
        addJButtonManageGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addJButtonManageGUIMouseClicked(evt);
            }
        });

        returnButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        returnButton.setText("Return");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        email1Button.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email1Button.setText("Email 1");

        email2Button.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email2Button.setText("Email 2");

        email3Button.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email3Button.setText("Email 3");

        email4Button.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email4Button.setText("Email 4");

        email5Button.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email5Button.setText("Email 5");

        email1Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        email2Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        email3Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        email4Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        email5Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleJLabelManageGUI)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email5Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(email4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(email5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addJButtonManageGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleJLabelManageGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email1Button))
                        .addGap(15, 15, 15)
                        .addComponent(email2Button))
                    .addComponent(email2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email3Button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(email4Button)
                        .addGap(18, 18, 18)
                        .addComponent(email5Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(email4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(email5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton)
                    .addComponent(addJButtonManageGUI))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonManageGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJButtonManageGUIMouseClicked
        new addGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addJButtonManageGUIMouseClicked

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
        new StartGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButtonManageGUI;
    private javax.swing.JButton email1Button;
    private javax.swing.JLabel email1Label;
    private javax.swing.JButton email2Button;
    private javax.swing.JLabel email2Label;
    private javax.swing.JButton email3Button;
    private javax.swing.JLabel email3Label;
    private javax.swing.JButton email4Button;
    private javax.swing.JLabel email4Label;
    private javax.swing.JButton email5Button;
    private javax.swing.JLabel email5Label;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel titleJLabelManageGUI;
    // End of variables declaration//GEN-END:variables
}
