/*
 * ® Copyright 2017 Haoran Wang. All rights reserved.
 *  
 * The works in this project are licenced under a 
 * Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported 
 * (CC BY-NC-SA 3.0) Licence.
 * 
 * That is to say, you may freely modify the work, quote the content of the work, 
 * and use it for other purposes, as long as it's non-commercial. 
 * If you want to distribute the work, you need to give appropriate credit and make 
 * sure it is under the same licence as the original, 
 * in this case, a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0) Licence should be applied.
 */


package haoran.wang.mailClient;

/**
 *
 * @author HaoranWang
 */
public class SendGUI extends javax.swing.JFrame {

    final void initializeEmailComboBox()
    {
        switch(data.numOfEmail)
        {
            case 1: emailsComboBox.removeAllItems();
                    emailsComboBox.addItem(data.email1.getName());
            case 2: emailsComboBox.removeAllItems();
                    emailsComboBox.addItem(data.email1.getName());
                    emailsComboBox.addItem(data.email2.getName());
            case 3: emailsComboBox.removeAllItems();
                    emailsComboBox.addItem(data.email1.getName());
                    emailsComboBox.addItem(data.email2.getName());
                    emailsComboBox.addItem(data.email3.getName());
            case 4: emailsComboBox.removeAllItems();
                    emailsComboBox.addItem(data.email1.getName());
                    emailsComboBox.addItem(data.email2.getName());
                    emailsComboBox.addItem(data.email3.getName());
                    emailsComboBox.addItem(data.email4.getName());
            case 5: emailsComboBox.removeAllItems();
                    emailsComboBox.addItem(data.email1.getName());
                    emailsComboBox.addItem(data.email2.getName());
                    emailsComboBox.addItem(data.email3.getName());
                    emailsComboBox.addItem(data.email4.getName());
                    emailsComboBox.addItem(data.email5.getName());
        }
    }
    
    // Constructor
    public SendGUI() {
        initComponents();
        initializeEmailComboBox();
    }

    /**
     * Code Generated by Netbeans® IDE
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        toJLableSendGUI = new javax.swing.JLabel();
        toJFieldSendGUI = new javax.swing.JTextField();
        subjectJLableSendGUI = new javax.swing.JLabel();
        messageJLabelSendGUI = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageJTextFieldSendGUI = new javax.swing.JTextArea();
        returnJButtonSendGUI = new javax.swing.JButton();
        sendJButtonSendGUI = new javax.swing.JButton();
        fromJLabelSendGUI = new javax.swing.JLabel();
        subjectJFieldSendGUI = new javax.swing.JTextField();
        emailsComboBox = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 450));

        toJLableSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        toJLableSendGUI.setText("To:");

        toJFieldSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        subjectJLableSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        subjectJLableSendGUI.setText("Subject");

        messageJLabelSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        messageJLabelSendGUI.setText("Message");

        messageJTextFieldSendGUI.setColumns(20);
        messageJTextFieldSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        messageJTextFieldSendGUI.setRows(5);
        jScrollPane1.setViewportView(messageJTextFieldSendGUI);

        returnJButtonSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        returnJButtonSendGUI.setText("Return");
        returnJButtonSendGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnJButtonSendGUIMouseClicked(evt);
            }
        });

        sendJButtonSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        sendJButtonSendGUI.setText("Send");
        sendJButtonSendGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendJButtonSendGUIMouseClicked(evt);
            }
        });

        fromJLabelSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fromJLabelSendGUI.setText("From:");

        subjectJFieldSendGUI.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        emailsComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromJLabelSendGUI)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnJButtonSendGUI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendJButtonSendGUI))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(messageJLabelSendGUI)
                    .addComponent(subjectJLableSendGUI)
                    .addComponent(toJLableSendGUI)
                    .addComponent(toJFieldSendGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(subjectJFieldSendGUI)
                    .addComponent(emailsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(toJLableSendGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toJFieldSendGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromJLabelSendGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subjectJLableSendGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectJFieldSendGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageJLabelSendGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnJButtonSendGUI)
                    .addComponent(sendJButtonSendGUI))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sendJButtonSendGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendJButtonSendGUIMouseClicked
        // Collect the information in the field and send them accordingly
        new sendEmail(toJFieldSendGUI.getText(), subjectJFieldSendGUI.getText(), messageJTextFieldSendGUI.getText());
    }//GEN-LAST:event_sendJButtonSendGUIMouseClicked

    private void returnJButtonSendGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnJButtonSendGUIMouseClicked
        new StartGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnJButtonSendGUIMouseClicked


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> emailsComboBox;
    private javax.swing.JLabel fromJLabelSendGUI;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageJLabelSendGUI;
    private javax.swing.JTextArea messageJTextFieldSendGUI;
    private javax.swing.JButton returnJButtonSendGUI;
    private javax.swing.JButton sendJButtonSendGUI;
    private javax.swing.JTextField subjectJFieldSendGUI;
    private javax.swing.JLabel subjectJLableSendGUI;
    private javax.swing.JTextField toJFieldSendGUI;
    private javax.swing.JLabel toJLableSendGUI;
    // End of variables declaration//GEN-END:variables
}
